version: "3.3"

services:
  app:
    image: node:20-bookworm-slim
    working_dir: /app
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 5173
      REDMINE_BASE_URL: http://redmine:3000
      REDMINE_API_KEY: ${REDMINE_API_KEY}
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    depends_on:
      - redmine
